name: Changelog Check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

concurrency:
  group: changelog-check-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-changelog') }}
    steps:
      - uses: actions/checkout@v6
      - uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: CHANGELOG.md
          missingUpdateErrorMessage: Please add an entry to CHANGELOG.md describing your change.
